### PR TITLE
Code cleanup activities based on output from phpcs.

### PR DESCRIPTION
**Pull request by traverus**

### CODE REVIEW

**Comment by coreylafferty** [comment]
Thanks for submitting this!  Putting this on hold temporarily given the imminent release of Gesso 3.1.  Once that's ready I'll rerun PHPCS on the new codebase and resolve any conflicts/issues.

**Comment by traverus** [comment]
Howdy, I merged / rerolled against the latest 8.x-3.x branch, had a little bit of time. Cheers.

**Comment by coreylafferty** [comment]
@traverus As is, this appears to blow away some changes in 8.x-3.x (e.g., the function documentation in the README), adds redundant file comments in some files (e.g., url.function.php), and has a conflict in the pattern-lab-config.json file.  Could you possibly pull down the latest 8.x-3.x and rerun this and create a new branch/PR (or otherwise 'start from scratch' for this branch) as I think some of its changes are based on old code.

**Comment by traverus** [comment]
Received, thanks!

**Pull request closed without merging**
