### PR TITLE
Create Componet

### PR DESCRIPTION
**Pull request by sbrack8t**
Add node script to automate component creation

### CODE REVIEW

**Comment by coreylafferty** [comment]
@sbrack8t Running this natively in Windows (not through Vagrant), this works as intended.

Running this on a PC, from inside Vagrant, I get this error:

`> gesso@0.1.0 component /vagrant/public/themes/gesso
> node component.js

/vagrant/public/themes/gesso/node_modules/inquirer/lib/prompts/list.js:32
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);
                                                             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.promptModule.restoreDefaultPrompts (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:77:28)

npm ERR! Linux 2.6.32-696.6.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "component"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! gesso@0.1.0 component: `node component.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gesso@0.1.0 component script 'node component.js'.
npm ERR! This is most likely a problem with the gesso package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node component.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gesso
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls gesso
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/public/themes/gesso/npm-debug.log`

**Comment by coreylafferty** [comment]
@sbrack8t i retested, but I see this when running inside Vagrant (on a PC).  I reran NPM install.

`[vagrant@vagrant gesso]$ npm run component

> gesso@0.1.0 component /vagrant/public/themes/gesso
> node component.js

/vagrant/public/themes/gesso/node_modules/inquirer/lib/prompts/list.js:32
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);
                                                             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.promptModule.restoreDefaultPrompts (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/vagrant/public/themes/gesso/node_modules/inquirer/lib/inquirer.js:77:28)

npm ERR! Linux 2.6.32-696.6.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "component"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! gesso@0.1.0 component: `node component.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gesso@0.1.0 component script 'node component.js'.
npm ERR! This is most likely a problem with the gesso package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node component.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gesso
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls gesso
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/public/themes/gesso/npm-debug.log`

**Comment by coreylafferty** [comment]
@sbrack8t this seems to be working as intended now.  The did some light testing trying to break it and the only thing I found was if I tell it a directory location that doesn't exist.  For example, if you put:

'04-template' (which is not an existing directory) instead of '04-templates' (which is),  you get this:

```
Component Location: /vagrant/public/themes/gesso/pattern-lab/source/_patterns/04-template/dirtest
? Is this what you want? Yes
dirtest created
{ Error: ENOENT: no such file or directory, mkdir '/vagrant/public/themes/gesso/pattern-lab/source/_patterns/04-template/dirtest'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/vagrant/public/themes/gesso/pattern-lab/source/_patterns/04-template/dirtest' }
```

Maybe that's fine, but it might be better if it gave an error when you put in the path that it wouldn't work.  My first thought was to just have a selection of folders... but then you couldn't put subfolders for variants (e.g., 03-components/menu as the location for menu--new).  So maybe it just tests if you put an initial root folder that exists and asks for a new location if it fails?  Or you could choose the root folder in one prompt and then add a subfolder in a second prompt?

What are your thoughts?

**Comment by sbrack8t** [comment]
@coreylafferty This should be good to go. The prompt will show a list of the current PL folders and give the option to add a subfolder. If your final choice already exists it will let you know and stop the script from overwriting the existing files

**Pull request merged**
