### PR TITLE
Add class transform plugin

### PR DESCRIPTION
**Pull request by sbrack8t**

### CODE REVIEW

**Review by dcmouyard — COMMENTED** [review]
I’m still seeing the following console errors in IE11:

```
SCRIPT1003: Expected ':'
primary-menu.min.js (133,1)
SCRIPT1003: Expected ':'
mobile-menu.min.js (109,1)
SCRIPT100: Syntax error
scripts.min.js (96,1)
```

**Comment by dcmouyard** [comment]
Removing `scripts.min.js` from the page still results in the primary & mobile menu scripts not working IE11.

**Comment by sbrack8t** [comment]
@dcmouyard I can't recreate this bug. I created a new sandbox environment, copied the theme and rebuilt the project. I tested the main menu and sub navs in Windows 10/IE 11 and everything is working as expected

**Comment by dcmouyard** [comment]
It turns out I was missing `.babelrc` in my Dockerfile, which meant `common.js` wasn’t getting compiled.

**Pull request closed without merging**
