### PR TITLE
adds details polyfill for older browsers and updates details components

### PR DESCRIPTION
**Pull request by coreylafferty**

### CODE REVIEW

**Review by dcmouyard — COMMENTED** [review]
This PR works for me in IE Edge and IE 11 when viewing the details component in Pattern Lab, but not in Drupal.

Strangely, when turning off JS aggregation the items on a node edit page that are usually in details end up in vertical tabs instead.

**Comment by dcmouyard** [comment]
I get the same details -> vertical tabs on node edit pages when JS aggregation is turned off on `8.x-3.x` so it’s not something introduced in this PR.

**Review by dcmouyard — APPROVED** [review]
After talking this through with Corey, we think the problem I had was due to #313 , and the un-aggregated JS polyfill worked for me when manually showing the details summary.

**Comment by kmonahan** [comment]
Was just about to ask if this was related to #313. I'm looking into that one now, but in the mean time, testing with `gulp build` rather than `gulp` should get you the proper behavior.

**Pull request merged**
