### PR TITLE
Icon link formatter

### PR DESCRIPTION
**Pull request by kmonahan**
Adds a new field formatter for icon links and modifies the existing button field formatter to allow for icons. Also adds a modifier classes field to both so that additional theme or component-specific classes can be added.

### CODE REVIEW

**Comment by kmonahan** [comment]
Drupal-specific: applies to GUS but not to any other Gessos

**Comment by coreylafferty** [comment]
@kmonahan This now has conflicts since the upgrades to all the story files have been merged. I started to fix things, but it got a bit complicated so I think I'll let you resolve these conflicts before I begin testing if that's ok.

**Comment by kmonahan** [comment]
@coreylafferty I won't be able to get to this until March, but I don't think there's a problem with letting it hang out for a bit.

**Review by coreylafferty — CHANGES_REQUESTED** [review]
Currently has conflicts with 5.x/5.x-RC. Please fix conflicts and then will retest.

**Comment by kmonahan** [comment]
@coreylafferty Updated to resolve merge conflicts

**Review by dcmouyard — APPROVED** [review]
Works like a charm!

**Review by coreylafferty — APPROVED** [review]

**Pull request merged**
